/*数据表结构*/

-- 1.user（用户表）
CREATE TABLE IF NOT EXISTS user (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(500) NOT NULL,
  email VARCHAR(50) NOT NULL,
  github VARCHAR(50),
  blog VARCHAR(50),
  head_portrait VARCHAR(100),
  mood VARCHAR(100),
  submit_count TINYINT NOT NULL DEFAULT 0,
  ac_num TINYINT NOT NULL DEFAULT 0,
  rating_num TINYINT NOT NULL DEFAULT 0,
  rating_score TINYINT  NOT NULL DEFAULT 0,
  `rank` TINYINT NOT NULL,
  role_id TINYINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
  CONSTRAINT uk_username UNIQUE KEY(username)
)

-- 2.user_certification（实名认证表）
CREATE TABLE IF NOT EXISTS user_certification (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  certification_id TINYINT NOT NULL,
  real_name VARCHAR(10) NOT NULL,
  sex ENUM('男', '女') NOT NULL,
  stu_id INT,
  school VARCHAR(20),
  faculty VARCHAR(20),
  major VARCHAR(20),
  class VARCHAR(20),
  phone VARCHAR(20),
  graduation_time VARCHAR(30),
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
)

-- 3.certification（认证类型）
CREATE TABLE IF NOT EXISTS certification (
  id TINYINT NOT NULL AUTO_INCREMENT,
  type VARCHAR(50) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
  CONSTRAINT type UNIQUE KEY(type)
)

-- 4.solved_problem（用户解决题目表）
CREATE TABLE IF NOT EXISTS solved_problem (
  id INT NOT NULL AUTO_INCREMENT,
  problem_id INT NOT NULL,
  user_id INT NOT NULL,
  submit_status VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
)

-- 5.admin（管理员表）
CREATE TABLE IF NOT EXISTS admin (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(500) NOT NULL,
  role_id TINYINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
  CONSTRAINT uk_username UNIQUE KEY(username)
)

-- 6.role（角色表）
CREATE TABLE IF NOT EXISTS role (
  id TINYINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  permissionCodes VARCHAR(255) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
  CONSTRAINT uk_username UNIQUE KEY(name)
)

-- 7.message（消息表）
CREATE TABLE IF NOT EXISTS message (
  id TINYINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(20) NOT NULL,
  content VARCHAR(500) NOT NULL,
  creator VARCHAR(50) NOT NULL,
  user_id INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
)

-- 8.announcement（公告表）
CREATE TABLE IF NOT EXISTS announcement (
  id TINYINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  creator VARCHAR(50) NOT NULL,
  source_id INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
)

-- 9.problem（题目表）
CREATE TABLE IF NOT EXISTS problem {
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  input VARCHAR(500) NOT NULL,
  output VARCHAR(500) NOT NULL,
  sample_input VARCHAR(300) NOT NULL,
  sample_output VARCHAR(300) NOT NULL,
  source_id INT NOT NULL,
  time_limit VARCHAR(20) NOT NULL,
  memory_limit VARCHAR(20) NOT NULL,
  io_mode VARCHAR(20) NOT NULL,
  level VARCHAR(10) NOT NULL,
  submit_count TINYINT NOT NULL DEFAULT 0,
  ac_count TINYINT NOT NULL DEFAULT 0,
  ac_num TINYINT NOT NULL DEFAULT 0,
  creator VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id),
}

-- 10.problem_judge_type（题目评测方式表）
CREATE TABLE IF NOT EXISTS problem_judge_type (
  id INT NOT NULL AUTO_INCREMENT,
  problem_id INT NOT NULL,
  judge_id TINYINT NOT NULL,
  reptile_problem_id INT,
  all_sample_input TEXT,
  all_sample_output TEXT,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)


-- 11.judge_type（评测方式标准表）
CREATE TABLE IF NOT EXISTS judge_type (
  id TINYINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  reptile_name VARCHAR(50),
  reptile_url VARCHAR(300),
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 12.tag（标签表）
CREATE TABLE IF NOT EXISTS tag (
  id TINYINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  creator VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 13.problem_tag（题目标签表）
CREATE TABLE IF NOT EXISTS problem_tag (
  id TINYINT NOT NULL AUTO_INCREMENT,
  problem_id INT NOT NULL,
  tag_id TINYINT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 14.judge（评测表）
CREATE TABLE IF NOT EXISTS judge (
  id TINYINT NOT NULL AUTO_INCREMENT,
  problem_id INT NOT NULL,
  code TEXT NOT NULL,
  time VARCHAR(20) NOT NULL,
  memory VARCHAR(20) NOT NULL,
  language VARCHAR(10) NOT NULL,
  submit_status VARCHAR(20) NOT NULL,
  source_id INT NOT NULL,
  creator VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 15.contest（竞赛信息表）
CREATE TABLE IF NOT EXISTS contest (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  entry_type VARCHAR(10) NOT NULL,
  rank_model VARCHAR(10) NOT NULL,
  running_status VARCHAR(10) NOT NULL,
  creator VARCHAR(20) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 16.contest_user（竞赛用户报名表）
CREATE TABLE IF NOT EXISTS contest_user (
  id INT NOT NULL AUTO_INCREMENT,
  contest_id INT NOT NULL,
  user_id INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  crt_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lm_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_id PRIMARY KEY(id)
)

-- 17.竞赛排名：还未考虑好是实时计算还是落地成表。